### PR TITLE
ImageMagick 7 support.

### PR DESCRIPTION
**Pull request by jhorowitz-firedrum**
Signed-off-by: Jonathan Horowitz <jhorowitz@firedrum.com>

### CODE REVIEW

**Comment by nordfalk** [comment]
Hi, thanks for your contribution.
This commit is very large, containing changes in whitespaces etc which makes it very hard to see what is needed.
Could you please make a pull request with only the absolutely minimal changes needed?

Yours,
Jacob

**Comment by jhorowitz-firedrum** [comment]
Sorry for the delay; I've rebased on latest master and removed a lot of the whitespace changes.

**Comment by nordfalk** [comment]
Hi jhorowitz,
It looks much nicer now, thank you.
However I still cannot merge it without a feeling that unknown things might break.

1) Im not using it myself anymore and cannot test it on different platforms. Are you sure it still works on Windows, Linux and Mac?

2) You are doing a lot of different things here:
- Updating the API to IM7 (https://github.com/techblue/jmagick/pull/35/commits/ef5f32b20c7186cbb0e79daaa134646e509074d9)
- Adding functionality (https://github.com/techblue/jmagick/pull/35/commits/2a7699d4566fa3f9a45df1cf15feba3d447962b4)
- Updating the build system (https://github.com/techblue/jmagick/pull/35/commits/ef5f32b20c7186cbb0e79daaa134646e509074d9)
- Moving stuff around
- Changing very big or binary files

Therefore I still have no overview of all your changes and can't be sure they wont break things. 
Another aspect: If I merge your changes and you have added a virus or worm in one of the big/binary files then I as maintainer would be the guilty guy that helped you inserting it.

I know it might be too much to ask of you but could you please make 3 seperate pull requests:
- Adding/minor updating which I can pull that without risk.
 (https://github.com/techblue/jmagick/pull/35/commits/2a7699d4566fa3f9a45df1cf15feba3d447962b4 and  https://github.com/techblue/jmagick/pull/35/commits/3adc49cfe3f4b9e5b365c7fdc5c3d3618f810205 and
https://github.com/techblue/jmagick/pull/35/commits/9f1c9e2234fda2d8e473fd1e4b59cfd125fe447d)

- One for updating the API to IM7  (with no big/binary changes)
- One for updating the build system (with no big/binary changes)

Yours,
Jacob

**Comment by jhorowitz-firedrum** [comment]
#37 covers the first bullet point of separating this out into 3 pull requests.

There are no binary changes, it is all within the source; if you mean ABI changes, that is required to use IM7, though it should still support compiling against IM6.

**Comment by jhorowitz-firedrum** [comment]
I can also vouch that the end result of all these pull requests builds on linux and windows, as this is currently being used in production for the [FireDrum Email Marketing](https://www.firedrumemailmarketing.com/) platform's image upload processing.

**Comment by jhorowitz-firedrum** [comment]
#38 covers the third bullet point of separating this out into 3 pull requests.

**Comment by jhorowitz-firedrum** [comment]
#43 covers the second bullet point of separating this out into 3 pull requests.

**Pull request closed without merging**
