### PR TITLE
Add: Kerning, InterwordSpacing, InterlineSpacing, getTypeMetrics, FormatMagickCaption

### PR DESCRIPTION
**Pull request by ferbar**
Hello,
I added some missing functions I needed

### CODE REVIEW

**Comment by ferbar** [comment]
Do you ned any assistance?
i think Kerning, InterwordSpacing, InterlineSpacing, getTypeMetrics, formatMagickCaption would be really useful

**Comment by ajkerr** [comment]
@ferbar Merging this is moving up my to do list - hoping to get to it very soon, sorry for the delay.

**Comment by ajkerr** [comment]
Thanks for the PR. I cherry-picked almost all of the commits and merged them into the master branch.

**Comment by ferbar** [comment]
cool!

Am Freitag, 26. Juni 2015, 06:05:27 schrieb Andrew Kerr:

**Pull request closed without merging**
